spring.application.name=bank-hits-account

server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

bank.master-account.number=00000000000000000001
bank.master-account.client-id=0
bank.master-account.initial-balance=100000000.00
bank.default-currency=RUB

exchange-rate.api.daily-url=https://www.cbr.ru/scripts/XML_daily_eng.asp
