services:
  db_user:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    networks: [appnet]
    volumes:
      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  service_user:
    build:
      context: ./bank-hits-user
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_user:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_user
      SPRING_DATASOURCE_PASSWORD: user_pass
      CLIENTS_ACCOUNT_URL: http://service_account:8080  # связь для Feign
    depends_on:
      db_user:
        condition: service_healthy
#      service-b:
#        condition: service_started
#      service-c:
#        condition: service_started
    networks: [appnet]
    ports:
      - "8081:8080"   # только если нужен доступ с хоста

  db_account:
    image: postgres:16
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_pass
    networks: [appnet]

  service_account:
    build: ./bank-hits-account
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_account:5432/account_db
      SPRING_DATASOURCE_USERNAME: account_user
      SPRING_DATASOURCE_PASSWORD: account_pass
    depends_on: [db_account]
    networks: [appnet]
    ports:
      - "8082:8080"
#
#  db_c:
#    image: postgres:16
#    environment:
#      POSTGRES_DB: c_db
#      POSTGRES_USER: c_user
#      POSTGRES_PASSWORD: c_pass
#    networks: [appnet]
#
#  service-c:
#    build: ./module-c
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db_c:5432/c_db
#      SPRING_DATASOURCE_USERNAME: c_user
#      SPRING_DATASOURCE_PASSWORD: c_pass
#    depends_on: [db_c]
#    networks: [appnet]
#    ports:
#      - "8083:8080"
#
networks:
  appnet: