spring.application.name=bank-hits-credit

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/credit_db
spring.datasource.username=credit_user
spring.datasource.password=credit_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

core.service.url=http://localhost:8082
monitoring.service-url=http://localhost:8087
monitoring.app=system
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [traceId=%X{traceId:-?}] %logger{25} - %msg%n

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

credit.payment.cron=0 * * * * *

bank.master-account-number=00000000000000000001
spring.task.scheduling.enabled=true
