spring.application.name=bank-hits-credit

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/credit_db
spring.datasource.username=credit_user
spring.datasource.password=credit_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

core.service.url=http://localhost:8081

credit.payment.cron=0 * * * * *

bank.master-account-number=00000000000000000001
spring.task.scheduling.enabled=true