# server
server.port=8085

# database ? ??? ????? ?? docker-compose, ?? localhost
spring.datasource.url=jdbc:postgresql://employee-db:5432/employee_backend_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# kafka ? ??? ??????????
spring.kafka.bootstrap-servers=kafka:9092

# downstream services ? ????? ???????????
services.account-service-url=http://localhost:8082
services.credit-service-url=http://localhost:8083
services.user-service-url=http://localhost:8081

# sso ? ???? ???
sso.base-url=http://sso-service:8085
sso.jwks-url=http://sso-service:8085/auth/.well-known/jwks.json
sso.authorization-url=http://sso-service:8085/auth/authorize
sso.client-id=employee-backend
sso.client-secret=secret
sso.redirect-uri=http://localhost:8082/bff/employee/auth/callback

app.frontend-url=http://localhost:4201
app.cookie-name=access_token