spring.application.name=sso-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/sso_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

sso.issuer=http://localhost:8086
sso.access-token-expiry-seconds=3600