spring.application.name=sso-service

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/sso_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

sso.issuer=http://localhost:8086
sso.access-token-expiry-seconds=3600
services.user-service-url=http://localhost:8081
sso.user-provisioning.max-attempts=10
sso.user-provisioning.retry-delay-ms=2000
app.seed.enabled=false
app.auth.default-password=password
app.seed.employee.name=Default Employee
app.seed.employee.email=employee@bank.local
app.seed.client.name=Default Client
app.seed.client.email=client@bank.local
